### ISSUE TITLE
enable `pip install` from within the provider

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#17]
### Why
We want ray worker running on provider to be able to get any needed libs from pip before starting the actual computations

### How
- [x] On worker side we should be able to run something like this:
   ```
    pip install --index-url https://pypi.dev.golem.network/simple redis
   ```
- [x]  We should be able to put pip command into yaml file to execute at the setup phase (for now it is ok to make user write --index-url, it might require hiding later though)

- [x] there is example of how this can be done in https://github.com/golemfactory/golem-kernel-python/tree/ms-misc

```[tasklist]
### Tasks
- [x] use manifest to allow outbound for pip in cluster manager
- [x] make sure the pip cmdline works from inside of the worker
```
