### ISSUE TITLE
Milestone: no ssh PoC

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#19]
### Why
- [x] Stop making users install sshd on their machines

### How
Same as https://github.com/golemfactory/golem-ray/milestone/1 but without ssh

- [x] `GolemNodeProvider` talks with `golem-core` 
- [x] manual `yagna` setup
- [x] local head commands are sent **without ssh**
- [x] no payments
- [x] one/two python+ray images
- [x] AUTOSCALER works
```[tasklist]
### Tasks
- [x] Integrate https://github.com/golemfactory/golem-ray/tree/local-command-runner
- [x] Verify ray up/down works properly without sshd server on local machine
- [x] Veriffy ray submit works properly too
```
