### ISSUE TITLE
Milestone: happy path works

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#20]
### Why
- [ ] We want to have working version with all components in place for testing and stabilization

### How
- [x] all components implemented with happy path passing
- [ ] `golem-ray` installable with pip
- [x] `yagna` setup hidden by `ray up`
- [ ] payments management in cluster.yaml
- [x] one/two specific image(s) supported

```[tasklist]
### Tasks
- [ ] #12
- [ ] #13
- [ ] setup `golem-ray` in `pip`
- [x] use poetry
- [ ] yagna installed by `ray up`
- [ ] yagna started/stopped by ray up/down (including default app_key being used automagically)
- [ ] payment network taken from cluster yaml (goerli as default when empty)
- [ ] import key from file specified in cluster yaml
- [ ] payments work
```
