### ISSUE TITLE
Milestone: budget control & nodes config in yaml

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#25]
### Why
- [ ] give users the control over the cluster and the costs

### How
- [ ] simple budget control mechanism definable in cluster yaml
- [ ] simple node definition mechanism definable in cluster yaml
```[tasklist]
### Tasks
- [ ] glm per hour limit in cluster yaml
- [ ] simple heuristics when to not start new nodes when limit would be endangered
- [ ] simple definition of node types in cluster yaml
- [ ] status in `golem-ray` showing current spendings
- [ ] forecast of spending for the next period of time (5 mins? 15 mins?)
- [ ] allow new nodes when forecast is under the limit
- [ ] stop existing nodes when forecast is over the limit
```
