### ISSUE TITLE
Milestone: docs

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#26]
### Why
- [ ] provide guidance for users to be able to use Ray on Golem on their own

### How
- [ ] packages released (and described)
- [ ] tutorials inside golem docs

```[tasklist]
### Tasks
- [ ] Make `golem-ray` repo public
- [x] Tutorial: run ray app on golem testnet
- [x] Tutorial: intro to ray (simple ray app)
- [ ] Benchmark: ray app run on Golem compared to run on GCP and AWS
```
