### ISSUE TITLE
Milestone: Ray on Golem Preview Program

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#27]
### Why
- [ ] Make first contact with Ray on Golem piece of cake (UX wise)

### How
- [ ] launch alpha
- [ ] run preview of the preview to spot issues with tasks
- [ ] fix tasks
- [ ] run preview to gather more feedback
```[tasklist]
### Tasks
- [ ] Prepare tasks
- [ ] Prepare release
- [ ] Release
- [ ] Run Preview of the Preview
- [ ] Analyse and act on preview of the preview feedback
- [ ] Run Preview
- [ ] Analyse and act on preview feedback
```
