### ISSUE TITLE
Milestone: pre-alpha release

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#28]
## Why
- [x] get ready for preview program to get UX feedback
- [x] show the community our status

### ray cli 
- [x] pre-alpha musts
  - [x] ray up golem-cluster.yaml works starts the head node 
  - [x] ray submit golem-cluster.yaml ray-app. executes 
  - [x] ray up gol cluster.yaml starts min_workers
  - [ ] ray up and ray submit tried on mainnet (so we know how much it doesn't work)
- [ ] pre-alpha shoulds
  - [ ] ray status works (10001 port forward ?)
  - [ ] ray cluster dump work 
  - [x] simple test works: ray submit "python -c 'import ray; ray.init()'"

### autoscaler
- [x] pre-alpha musts
  - [x] adding nodes when work queue rises
- [x] pre-alpha shoulds
  - [x] deleting nodes when work idle

### py & ray versions / images
- [x] pre-alpha musts
  - [x] one working image py 3.10.12 (ubuntu 22.04) + 1 working ray version 
  - [x] image hash on cluster yaml (for manual support of other versions) 
  - [x] images uploaded into golem/ray-on-golem registry repo 
- [ ] pre-alpha shoulds
  - [x] dev cluster config with newer files mounted 
  - [x] warning if the version mismatch 
  - [x] Image tag in yaml (for manual support of other versions) 
  - [ ] python & ray versions checked and proper image requested 
  - [ ] many working images (py 3.8.17, 3.10.6 (ubuntu 22.04), 3.10.12 (newest 3.10), 3.11 + ray >=2.5 (the one we work with now)
  - [x] socket.gethostbyname(socket.gethostname()) works. (on ray-poc it doesn't) 

### payments
- [x] pre-alpha musts
  - [x] testnet payments accepting all invoices 
  - [x] accept invoices also on C-c

### ray-on-golem cli 
- [x] pre-alpha musts
  - [x] pip install ray-on-golem (no yagna dependency) 
  - [x] started manually 
  - [x] poetry instead of setup.py 
- [x] pre-alpha shoulds
  - [x] more exotic port than 8080 (it might be busy) 
  - [x] ray-on-golem port configured (yaml) 
  - [x] ray-on-golem started with ray up 

### yaml 
- [x] pre-alpha musts
  - [x] minimalistic yaml without any not needed things 
  - [x] nice comments in golem-cluster.yaml explaining all the stuff 
- [x] pre-alpha shoulds
  - [x] pip install works from yaml 

### yagna 
- [x] pre-alpha musts
  - [x] yagna installed manually 
  - [x] "ray-on-golem" app-key autoconfigured and/or used 
- [ ] pre-alpha shoulds
  - [x] yagna installed by ray-on-golem or ray up 
  - [x] yagna configured by ray-on-golem or ray up 

### budget control
- [x] none

### nodes config 
- [x] none

### docs 
- [x] pre-alpha musts
  - [x] one crude tutorial runing example app on testnet listing missing features and calling for feedback, with one sample app (pi or ip listing)
  - [x] ray-on-golem repo public
  - [x] 2-3 example ray apps (task one, bridge one)
  - [x] yt movie proving it actually works
  - [x] websocat installation instructions
  - [x] github readme (to be copied to pypi)
  - [x] our yaml reference
- [ ] pre-alpha shoulds
  - [ ] mandelbrot example
  - [ ] example cluster.yaml and ray app visible in a nice place as eg golem.network/ray/...

### ray docs
  - [x] no presense

### quality
- [x] pre-alpha musts
  - [x] refactored code 
  - [x] manual testing

### visibility of ray-on-golem
- [x] pre-alpha musts
  - [x] reverse ssh tunel from local machine to head - ray-on-golem visibility
- [ ] pre-alpha shoulds
  - [ ] tunel with socat to avoid encrypting (performance)

### messiness of output
- [x] pre-alpha musts
  - [x] real messiness allowed 
- [x] pre-alpha shoulds
  - [x] messages outputed have some meaning and are not much more than when running aws (both ray-on-golem and ray up)

### usage stats
- [x] pre-alpha musts
  - [x] golem-registry used to get usage stats (both download and resolve)
  - [x] Image tag in cluster.yaml 
  - [x] tags: golem/ray-on-golem:py3.1 0.6- ray2.5.1 
  
### head node HA
- [x] head node on provider / no HA

### fault tolerance
- [x] none

### other ray modules
- [x] none

### ssh
- [x] pre-alpha musts
  - [x] websocat proxy to the head
  - [x] don't require user to feed their public key to yaml - we want to generate temporary keys just for Ray on Golem
- [x] pre-alpha shoulds
  - [x] websocat proxy to all the workers (so user can easily ssh to workers and see)

### supported platforms
- [x] pre-alpha musts
  - [x] Linux

### benchmarks
- [x] pre-alpha musts
  - [x] none
- [ ] pre-alpha shoulds
  - [ ] why dds (bridge app) works faster on ray-poc than on AWS

### legals
- [x] pre-alpha musts
  - [x] can we use ray on golem name and logo
  - [x] do we need some licensing information anywhere?

### yagna / sdk features
- [x] none

### preview / feedback
- [x] pre-alpha musts
  - [x] prepare tasks for Preview Program 1
  - [x] feedback form to create a place for voicing unrelated opinions
  - [x] prepare Preview feedback submission mechanism
