### ISSUE TITLE
Milestone: `ray up` + `golem-core` PoC

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#6]
### Why
- [x] Verify `autoscaler` can work with `golem-core`
- [x] Draft all components and make them work together

### How
- [x] `GolemNodeProvider` talks to running `golem-ray`
- [x] manual `golem-ray` start
- [x] manual `yagna` setup
- [x] local head commands are sent via ssh
- [x] no payments
- [x] one/two python+ray images
- [x] AUTOSCALER works

```[tasklist]
### Todo
- [ ] https://github.com/golemfactory/golem-ray/issues/10
- [ ] https://github.com/golemfactory/golem-ray/issues/17
- [ ] https://github.com/golemfactory/golem-ray/issues/22
- [ ] https://github.com/golemfactory/golem-ray/issues/7
- [ ] https://github.com/golemfactory/golem-ray/issues/9
- [x] Start worker nodes via `GolemNodeProvider`
- [x] Terminate node when autoscaler requests
- [x] Implement other missing and needed `GolemNodeProvider` methods
- [x] Verify that `ray submit` works
- [ ] Start golem-ray with `ray up` command
- [ ] Automate (bash script?) starting everything up and triggerring autoscaler
- [ ] Quality to control regression in the future
```
