### ISSUE TITLE
Milestone: mvp release

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ray-on-golem#77]
## Why
- [ ] Provide information on viability in two scenarios 
   🐍 Ray on Golem as a gateway to Golem for python devs
   🤖 Ray on Golem as a tool for AI/ML people

## What

- [ ] Effortless 4-step UX
  - [x]  ray-on-golem installed from pypi
  - [x]  clear and well-documented yaml
  - [x]  yagna installed under the hood
  - [x]  multiple python+ray versions images available
  - [ ]  head node high availability approached

- [ ] Budget control
  - [x]  Mainnet payments not exceeding the limit from yaml
  - [x]  Some control over node specs

- [ ] Mainnet benchmarks
  - [ ]  Show it can be done on mainnet
  - [ ]  Show comparison with AWS / GCP (performance, ux & prices)

- [ ] Get feedback & usage
  - [ ]  Preview program
  - [ ]  Contest for real-world apps  
  - [ ]  Ray docs / community presence
